/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cards */
        get: operations["list_cards_v1_cards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Card */
        get: operations["get_card_v1_cards__card_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cards/{card_id}/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Mapping */
        post: operations["create_mapping_v1_cards__card_id__mappings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cards/{card_id}/memo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Memo */
        get: operations["get_memo_v1_cards__card_id__memo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Data Snapshots */
        get: operations["list_data_snapshots_v1_data_snapshots_get"];
        put?: never;
        /** Create Data Snapshot */
        post: operations["create_data_snapshot_v1_data_snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data-snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Data Snapshot */
        get: operations["get_data_snapshot_v1_data_snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Extractions */
        get: operations["list_extractions_v1_extractions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/extractions/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Extraction */
        get: operations["get_extraction_v1_extractions__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mappings */
        get: operations["list_mappings_v1_mappings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mappings/{mapping_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mapping */
        get: operations["get_mapping_v1_mappings__mapping_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-versions/{source_version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source Version */
        get: operations["get_source_version_v1_source_versions__source_version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-versions/{source_version_id}/extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Extraction */
        post: operations["create_extraction_v1_source_versions__source_version_id__extractions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_v1_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["get_source_v1_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Source Version */
        post: operations["add_source_version_v1_sources__source_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionRuleEvidence */
        ActionRuleEvidence: {
            /** Claim Ids */
            claim_ids: string[];
            state: components["schemas"]["EvidenceState"];
        };
        /** AdapterProfile */
        AdapterProfile: {
            /** Adapter Id */
            adapter_id: string;
            /** Adapter Version */
            adapter_version: string;
            /** Capabilities */
            capabilities: components["schemas"]["DataCapability"][];
            /** Dataset Id */
            dataset_id: string;
            /** Product Id */
            product_id: string;
            /** Provider Id */
            provider_id: string;
            /** Schema Bindings */
            schema_bindings: components["schemas"]["SchemaBinding"][];
            /** Synthetic */
            synthetic: boolean;
            use_rights: components["schemas"]["UseRightsIdentity"];
        };
        /**
         * AdapterUnavailableReason
         * @enum {string}
         */
        AdapterUnavailableReason: "credentials_unavailable" | "capability_unavailable" | "entitlement_unavailable" | "configuration_unavailable";
        /** AdapterUnavailableResult */
        AdapterUnavailableResult: {
            /** Adapter Id */
            adapter_id: string;
            /** Adapter Version */
            adapter_version: string;
            capability: components["schemas"]["DataCapability"];
            /** Dataset Id */
            dataset_id: string;
            /** Entitlement Id */
            entitlement_id: string;
            /** Product Id */
            product_id: string;
            /** Provider Id */
            provider_id: string;
            reason_code: components["schemas"]["AdapterUnavailableReason"];
            /** Sanitized Message */
            sanitized_message: string;
            /**
             * Status
             * @default unavailable
             * @constant
             */
            status: "unavailable";
            /** Use Rights Id */
            use_rights_id: string;
        };
        /**
         * AdjustmentBasis
         * @enum {string}
         */
        AdjustmentBasis: "raw_unadjusted" | "as_of_adjusted";
        /**
         * AmbiguityFlag
         * @enum {string}
         */
        AmbiguityFlag: "synthetic_fixture" | "source_url_not_retrieved" | "social_manipulation_risk" | "official_corroboration_required" | "missing_action_rule" | "ambiguous_action_rule" | "missing_forecast_horizon" | "ambiguous_forecast_horizon" | "missing_raw_text";
        /** AsReportedFundamentalPayload */
        AsReportedFundamentalPayload: {
            /** Amendment Sequence */
            amendment_sequence: number;
            /**
             * As Reported
             * @default true
             * @constant
             */
            as_reported: true;
            /** Concept Id */
            concept_id: string;
            /**
             * Filing Accepted At
             * Format: date-time
             */
            filing_accepted_at: string;
            /**
             * Fiscal Period End
             * Format: date
             */
            fiscal_period_end: string;
            /**
             * Fiscal Period Start
             * Format: date
             */
            fiscal_period_start: string;
            fiscal_period_type: components["schemas"]["FiscalPeriodType"];
            /** Official Document Id */
            official_document_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "as_reported_fundamental";
            /** Restates Revision Id */
            restates_revision_id?: string | null;
            /** Value */
            value: string | null;
        };
        /**
         * AssetClass
         * @enum {string}
         */
        AssetClass: "equity" | "etf" | "futures" | "options" | "multi_asset";
        /** AssetClassEvidence */
        AssetClassEvidence: {
            /** Claim Ids */
            claim_ids: string[];
            state: components["schemas"]["EvidenceState"];
            value: components["schemas"]["AssetClass"] | null;
        };
        /**
         * AuthorityVerificationMethod
         * @enum {string}
         */
        AuthorityVerificationMethod: "manual_user_attestation" | "synthetic_fixture";
        /** AuthorizedMappingIdentity */
        AuthorizedMappingIdentity: {
            canonical_family: components["schemas"]["CanonicalFamily"];
            /** Mapper Rule Set Sha256 */
            mapper_rule_set_sha256: string;
            /** Mapper Rule Set Version */
            mapper_rule_set_version: string;
            /**
             * Mapping Id
             * Format: uuid
             */
            mapping_id: string;
            /** Mapping Input Sha256 */
            mapping_input_sha256: string;
            /** Mapping Version */
            mapping_version: number;
            /**
             * Official Corroboration Source Version Ids
             * @default []
             */
            official_corroboration_source_version_ids: string[];
            verdict: components["schemas"]["ResearchVerdict"];
        };
        /**
         * AvailabilityConvention
         * @enum {string}
         */
        AvailabilityConvention: "source_timestamp" | "phase4-date-only-next-day-v1";
        /**
         * AvailabilityPrecision
         * @enum {string}
         */
        AvailabilityPrecision: "timestamp" | "date";
        /**
         * BarInterval
         * @enum {string}
         */
        BarInterval: "P1D";
        /** CalendarSessionPayload */
        CalendarSessionPayload: {
            /** Close At */
            close_at: string | null;
            /** Early Close */
            early_close: boolean;
            /** Open At */
            open_at: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "calendar_session";
            /**
             * Session Date
             * Format: date
             */
            session_date: string;
            status: components["schemas"]["CalendarSessionStatus"];
        };
        /**
         * CalendarSessionStatus
         * @enum {string}
         */
        CalendarSessionStatus: "open" | "closed";
        /**
         * CanonicalFamily
         * @enum {string}
         */
        CanonicalFamily: "A_CROSS_SECTIONAL_EQUITY_RANKING" | "B_TIME_SERIES_MOMENTUM_REGIME" | "C_OFFICIAL_EVENT_TEXT_OVERLAY" | "D_PAIRS_STATISTICAL_ARBITRAGE" | "E_ORDER_BOOK_MICROSTRUCTURE" | "F_OPTIONS_FLOW_IV_RV_ANALYTICS";
        /** CardWithMemo */
        CardWithMemo: {
            card: components["schemas"]["TradingIdeaCard"];
            memo: components["schemas"]["ResearchMemo"];
        };
        /**
         * ConstituentDisposition
         * @enum {string}
         */
        ConstituentDisposition: "included_as_of" | "retained_historical_vintage" | "explicit_missingness";
        /**
         * ContentState
         * @enum {string}
         */
        ContentState: "supplied_text" | "retrieved_text" | "url_only_unretrieved";
        /**
         * ContributionStatus
         * @enum {string}
         */
        ContributionStatus: "not_blocked_by_corroboration" | "blocked_official_corroboration_required";
        /** CorporateActionPayload */
        CorporateActionPayload: {
            action_type: components["schemas"]["CorporateActionType"];
            /**
             * Announcement At
             * Format: date-time
             */
            announcement_at: string;
            /** Cash Amount */
            cash_amount?: string | null;
            /** Corporate Action Id */
            corporate_action_id: string;
            /**
             * Effective At
             * Format: date-time
             */
            effective_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "corporate_action";
            /** Split Ratio */
            split_ratio?: string | null;
            /** Target Instrument Id */
            target_instrument_id?: string | null;
        };
        /**
         * CorporateActionType
         * @enum {string}
         */
        CorporateActionType: "split" | "cash_dividend" | "merger" | "spinoff";
        /**
         * CorroborationStatus
         * @enum {string}
         */
        CorroborationStatus: "not_required" | "missing" | "linked_unverified" | "verified";
        /**
         * DataCapability
         * @enum {string}
         */
        DataCapability: "security_master" | "universe_membership" | "ohlcv" | "corporate_actions" | "delistings" | "as_reported_fundamentals" | "trading_calendar" | "volatility_return_inputs" | "official_document_event_metadata";
        /**
         * DataQualityCode
         * @enum {string}
         */
        DataQualityCode: "synthetic_fixture" | "date_only_convention_applied" | "future_availability_excluded" | "near_duplicate_retained" | "exact_duplicate_key" | "required_field_missing" | "invalid_enum_value" | "invalid_timestamp_order" | "orphan_reference" | "raw_normalized_lineage_gap" | "unit_currency_calendar_timezone_mismatch" | "schema_drift" | "current_universe_leakage" | "restatement_leakage" | "corporate_action_lookahead" | "missing_delisting_return" | "future_availability_included" | "unnormalized_rejected";
        /** DataQualityFinding */
        DataQualityFinding: {
            /** Affected Record Identity */
            affected_record_identity?: string | null;
            affected_record_type?: components["schemas"]["DataRecordType"] | null;
            code: components["schemas"]["DataQualityCode"];
            disposition: components["schemas"]["FindingDisposition"];
            /** Field Name */
            field_name?: string | null;
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            /** Finding Sha256 */
            finding_sha256: string;
            /** Normalized Content Sha256 */
            normalized_content_sha256?: string | null;
            /** Occurrence Count */
            occurrence_count: number;
            /** Occurrence Rate */
            occurrence_rate?: string | null;
            /** Range End Utc */
            range_end_utc?: string | null;
            /** Range Start Utc */
            range_start_utc?: string | null;
            /** Raw Payload Sha256 */
            raw_payload_sha256?: string | null;
            /** Rule Id */
            rule_id: string;
            /**
             * Rule Set Version
             * @default phase4-data-quality-v1
             * @constant
             */
            rule_set_version: "phase4-data-quality-v1";
            /** Sanitized Detail */
            sanitized_detail: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            severity: components["schemas"]["DataQualitySeverity"];
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** Snapshot Sha256 */
            snapshot_sha256: string;
        };
        /** DataQualityFindingDraft */
        DataQualityFindingDraft: {
            /** Affected Record Identity */
            affected_record_identity?: string | null;
            affected_record_type?: components["schemas"]["DataRecordType"] | null;
            code: components["schemas"]["DataQualityCode"];
            disposition: components["schemas"]["FindingDisposition"];
            /** Field Name */
            field_name?: string | null;
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            /** Finding Sha256 */
            finding_sha256: string;
            /** Normalized Content Sha256 */
            normalized_content_sha256?: string | null;
            /** Occurrence Count */
            occurrence_count: number;
            /** Occurrence Rate */
            occurrence_rate?: string | null;
            /** Range End Utc */
            range_end_utc?: string | null;
            /** Range Start Utc */
            range_start_utc?: string | null;
            /** Raw Payload Sha256 */
            raw_payload_sha256?: string | null;
            /** Rule Id */
            rule_id: string;
            /**
             * Rule Set Version
             * @default phase4-data-quality-v1
             * @constant
             */
            rule_set_version: "phase4-data-quality-v1";
            /** Sanitized Detail */
            sanitized_detail: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            severity: components["schemas"]["DataQualitySeverity"];
        };
        /**
         * DataQualitySeverity
         * @enum {string}
         */
        DataQualitySeverity: "info" | "warning" | "error" | "blocking";
        /**
         * DataRecordType
         * @enum {string}
         */
        DataRecordType: "instrument_identity" | "listing_identity" | "universe_membership" | "ohlcv_bar" | "corporate_action" | "delisting_event" | "as_reported_fundamental" | "calendar_session" | "official_document_event" | "volatility_return_input";
        /** DataSnapshot */
        DataSnapshot: {
            /** Active Constituent Count */
            active_constituent_count: number;
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            manifest: components["schemas"]["SnapshotManifest"];
            /** Normalized Observation Count */
            normalized_observation_count: number;
            /** Quality Finding Count */
            quality_finding_count: number;
            quality_status: components["schemas"]["SnapshotQualityStatus"];
            /** Raw Observation Count */
            raw_observation_count: number;
            /** Revision Count */
            revision_count: number;
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** Snapshot Sha256 */
            snapshot_sha256: string;
        };
        /** DelistingEventPayload */
        DelistingEventPayload: {
            /** Delisting Event Id */
            delisting_event_id: string;
            /** Delisting Return */
            delisting_return: string | null;
            delisting_type: components["schemas"]["DelistingType"];
            /**
             * Effective At
             * Format: date-time
             */
            effective_at: string;
            /**
             * Last Trade At
             * Format: date-time
             */
            last_trade_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "delisting_event";
            return_inclusion: components["schemas"]["DelistingReturnInclusion"];
        };
        /**
         * DelistingReturnInclusion
         * @enum {string}
         */
        DelistingReturnInclusion: "separate_return_required" | "provider_total_return_includes";
        /**
         * DelistingType
         * @enum {string}
         */
        DelistingType: "merger" | "bankruptcy" | "liquidation" | "exchange_removal" | "other";
        /** DependencyStatus */
        DependencyStatus: {
            /**
             * Postgres
             * @default ok
             * @constant
             */
            postgres: "ok";
            /**
             * Redis
             * @default ok
             * @constant
             */
            redis: "ok";
        };
        /**
         * EvidenceState
         * @enum {string}
         */
        EvidenceState: "source_supported" | "not_stated" | "ambiguous" | "not_applicable";
        /**
         * ExecutionStyle
         * @enum {string}
         */
        ExecutionStyle: "high_frequency_claim" | "intraday_claim" | "periodic_research_claim" | "read_only_analytics_claim";
        /** ExecutionStyleEvidence */
        ExecutionStyleEvidence: {
            /** Claim Ids */
            claim_ids: string[];
            state: components["schemas"]["EvidenceState"];
            value: components["schemas"]["ExecutionStyle"] | null;
        };
        /**
         * ExtractionEventType
         * @enum {string}
         */
        ExtractionEventType: "requested" | "queued" | "enqueue_failed" | "started" | "succeeded" | "failed";
        /** ExtractionRequestRecord */
        ExtractionRequestRecord: {
            /** Extraction Config Sha256 */
            extraction_config_sha256: string;
            /** Extraction Model Id */
            extraction_model_id?: string | null;
            /** Extraction Model Revision */
            extraction_model_revision?: string | null;
            /** Extraction Prompt Sha256 */
            extraction_prompt_sha256?: string | null;
            /** Extraction Prompt Version */
            extraction_prompt_version?: string | null;
            /**
             * Extraction Request Id
             * Format: uuid
             */
            extraction_request_id: string;
            /**
             * Extraction Schema Version
             * @default phase2-trading-idea-card-v2
             */
            extraction_schema_version: string;
            /**
             * Extractor Id
             * @default fable5-deterministic-extractor
             */
            extractor_id: string;
            /** @default deterministic_mock */
            extractor_kind: components["schemas"]["ExtractorKind"];
            /**
             * Extractor Version
             * @default 1
             */
            extractor_version: string;
            latest_event: components["schemas"]["ExtractionEventType"];
            /** Request Fingerprint */
            request_fingerprint: string;
            /**
             * Requested At Utc
             * Format: date-time
             */
            requested_at_utc: string;
            /** Rq Job Id */
            rq_job_id: string;
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
        };
        /**
         * ExtractorKind
         * @enum {string}
         */
        ExtractorKind: "deterministic_mock" | "llm";
        /** FieldMissingness */
        FieldMissingness: {
            /** Field Name */
            field_name: string;
            reason: components["schemas"]["MissingnessReason"];
            /** Source Detail Code */
            source_detail_code?: string | null;
        };
        /**
         * FindingDisposition
         * @enum {string}
         */
        FindingDisposition: "retained" | "excluded" | "blocked";
        /**
         * FiscalPeriodType
         * @enum {string}
         */
        FiscalPeriodType: "quarter" | "year" | "trailing_twelve_months";
        /**
         * ForecastHorizon
         * @enum {string}
         */
        ForecastHorizon: "sub_minute" | "intraday" | "next_day" | "multi_day" | "weekly" | "monthly";
        /** ForecastHorizonEvidence */
        ForecastHorizonEvidence: {
            /** Claim Ids */
            claim_ids: string[];
            state: components["schemas"]["EvidenceState"];
            value: components["schemas"]["ForecastHorizon"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Mode
             * @default research-paper-only
             * @constant
             */
            mode: "research-paper-only";
            /**
             * Service
             * @default api
             * @constant
             */
            service: "api";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * InfraRisk
         * @enum {string}
         */
        InfraRisk: "unknown" | "low" | "medium" | "high";
        /** InstrumentIdentityPayload */
        InstrumentIdentityPayload: {
            /** Country Code */
            country_code: string;
            instrument_type: components["schemas"]["InstrumentType"];
            /** Issuer Id */
            issuer_id: string;
            /** Legal Name */
            legal_name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "instrument_identity";
            /** Share Class Id */
            share_class_id: string;
        };
        /**
         * InstrumentType
         * @enum {string}
         */
        InstrumentType: "common_stock" | "etf";
        JsonValue: unknown;
        /** ListingIdentityPayload */
        ListingIdentityPayload: {
            /** Exchange Mic */
            exchange_mic: string;
            /** Primary Listing */
            primary_listing: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "listing_identity";
            status: components["schemas"]["ListingStatus"];
            /** Symbol */
            symbol: string;
        };
        /**
         * ListingStatus
         * @enum {string}
         */
        ListingStatus: "active" | "inactive" | "delisted";
        /** MappingEvidenceReference */
        MappingEvidenceReference: {
            /**
             * Claim Ids
             * @default []
             */
            claim_ids: string[];
            /**
             * Phase2 Field
             * @enum {string}
             */
            phase2_field: "signal_family" | "forecast_horizon" | "execution_style" | "required_data" | "testability" | "infra_risk" | "contribution_status" | "corroboration_status";
            state?: components["schemas"]["EvidenceState"] | null;
            /** Value */
            value?: string | null;
        };
        /** MappingRationale */
        MappingRationale: {
            /** Content Sha256 */
            content_sha256: string;
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            /**
             * Mapping Id
             * Format: uuid
             */
            mapping_id: string;
            /** Markdown */
            markdown: string;
            /**
             * Rationale Id
             * Format: uuid
             */
            rationale_id: string;
            /** Template Version */
            template_version: string;
        };
        /**
         * MappingReasonCode
         * @enum {string}
         */
        MappingReasonCode: "missing_raw_text" | "missing_action_rule" | "ambiguous_action_rule" | "missing_forecast_horizon" | "ambiguous_forecast_horizon" | "MISSING_CANONICAL_FAMILY" | "AMBIGUOUS_CANONICAL_FAMILY" | "PLATFORM_INFRASTRUCTURE_MISMATCH" | "OFFICIAL_CORROBORATION_REQUIRED" | "BORROW_AND_BREAK_REQUIREMENTS" | "READ_ONLY_ANALYTICS_ONLY" | "CANON_A_RULE_MATCHED" | "CANON_B_RULE_MATCHED" | "CANON_C_RULE_MATCHED";
        /**
         * MappingRuleId
         * @enum {string}
         */
        MappingRuleId: "P3-001-NON-TESTABLE-PRECEDENCE" | "P3-002-PLATFORM-MISMATCH" | "P3-003-SOCIAL-CORROBORATION" | "P3-004-PAIRS-REQUIREMENTS" | "P3-005-OPTIONS-READ-ONLY" | "P3-CANON-A" | "P3-CANON-B" | "P3-CANON-C" | "P3-CANON-D" | "P3-CANON-E" | "P3-CANON-F";
        /** MappingWithRationale */
        MappingWithRationale: {
            mapping: components["schemas"]["ResearchMapping"];
            rationale: components["schemas"]["MappingRationale"];
        };
        /**
         * MembershipStatus
         * @enum {string}
         */
        MembershipStatus: "included" | "excluded";
        /**
         * MissingnessReason
         * @enum {string}
         */
        MissingnessReason: "not_applicable" | "not_provided_by_source" | "not_yet_available_as_of" | "entitlement_restricted" | "unresolved_identity" | "delisting_return_not_provided" | "provider_return_already_includes_delisting";
        /** MockConfigurationIdentity */
        MockConfigurationIdentity: {
            /** Configuration Id */
            configuration_id: string;
            /** Configuration Sha256 */
            configuration_sha256: string;
            /**
             * Fixture Set Version
             * @default phase4-synthetic-pit-fixtures-v1
             * @constant
             */
            fixture_set_version: "phase4-synthetic-pit-fixtures-v1";
        };
        /** NormalizedObservation */
        NormalizedObservation: {
            /** Adapter Id */
            adapter_id: string;
            /** Adapter Version */
            adapter_version: string;
            availability_convention: components["schemas"]["AvailabilityConvention"];
            availability_precision: components["schemas"]["AvailabilityPrecision"];
            /** Availability Source Date */
            availability_source_date?: string | null;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Calendar Id */
            calendar_id: string | null;
            /** Currency */
            currency: string | null;
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Schema Id */
            dataset_schema_id: string;
            /** Dataset Schema Version */
            dataset_schema_version: string;
            /** Entitlement Id */
            entitlement_id: string;
            /**
             * Envelope Schema Version
             * @default phase4-normalized-observation-v1
             * @constant
             */
            envelope_schema_version: "phase4-normalized-observation-v1";
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * Field Missingness
             * @default []
             */
            field_missingness: components["schemas"]["FieldMissingness"][];
            /** Instrument Id */
            instrument_id: string | null;
            /** Listing Id */
            listing_id: string | null;
            /** Logical Record Id */
            logical_record_id: string;
            /** Logical Record Key Sha256 */
            logical_record_key_sha256: string;
            /** Normalized Content Sha256 */
            normalized_content_sha256: string;
            /**
             * Normalized Observation Id
             * Format: uuid
             */
            normalized_observation_id: string;
            /**
             * Observation Revision Id
             * Format: uuid
             */
            observation_revision_id: string;
            /** Payload */
            payload: components["schemas"]["InstrumentIdentityPayload"] | components["schemas"]["ListingIdentityPayload"] | components["schemas"]["UniverseMembershipPayload"] | components["schemas"]["OhlcvBarPayload"] | components["schemas"]["CorporateActionPayload"] | components["schemas"]["DelistingEventPayload"] | components["schemas"]["AsReportedFundamentalPayload"] | components["schemas"]["CalendarSessionPayload"] | components["schemas"]["OfficialDocumentEventPayload"] | components["schemas"]["VolatilityReturnInputPayload"];
            /** Product Id */
            product_id: string;
            /** Provider Id */
            provider_id: string;
            /**
             * Quality Flags
             * @default []
             */
            quality_flags: components["schemas"]["QualityFlag"][];
            /**
             * Raw Observation Id
             * Format: uuid
             */
            raw_observation_id: string;
            /** Raw Payload Sha256 */
            raw_payload_sha256: string;
            /** Retrieved At */
            retrieved_at: string | null;
            /** Revision Id */
            revision_id: string;
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** Snapshot Sha256 */
            snapshot_sha256: string;
            /** Source Record Id */
            source_record_id: string;
            /** Source Timezone */
            source_timezone: string;
            /** Unit */
            unit: string | null;
            /** Use Rights Id */
            use_rights_id: string;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
            /** Vintage Id */
            vintage_id: string;
        };
        /** ObservationRevision */
        ObservationRevision: {
            /** Adapter Id */
            adapter_id: string;
            /** Adapter Version */
            adapter_version: string;
            availability_convention: components["schemas"]["AvailabilityConvention"];
            availability_precision: components["schemas"]["AvailabilityPrecision"];
            /** Availability Source Date */
            availability_source_date?: string | null;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Calendar Id */
            calendar_id: string | null;
            /** Currency */
            currency: string | null;
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Schema Id */
            dataset_schema_id: string;
            /** Dataset Schema Version */
            dataset_schema_version: string;
            /** Entitlement Id */
            entitlement_id: string;
            /**
             * Envelope Schema Version
             * @default phase4-normalized-observation-v1
             * @constant
             */
            envelope_schema_version: "phase4-normalized-observation-v1";
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * Field Missingness
             * @default []
             */
            field_missingness: components["schemas"]["FieldMissingness"][];
            /** Instrument Id */
            instrument_id: string | null;
            /** Listing Id */
            listing_id: string | null;
            /** Logical Record Id */
            logical_record_id: string;
            /** Logical Record Key Sha256 */
            logical_record_key_sha256: string;
            /** Predecessor Revision Record Id */
            predecessor_revision_record_id?: string | null;
            /** Product Id */
            product_id: string;
            /** Provider Id */
            provider_id: string;
            /**
             * Quality Flags
             * @default []
             */
            quality_flags: components["schemas"]["QualityFlag"][];
            /**
             * Raw Observation Id
             * Format: uuid
             */
            raw_observation_id: string;
            /** Raw Payload Sha256 */
            raw_payload_sha256: string;
            /** Retrieved At */
            retrieved_at: string | null;
            /** Revision Content Sha256 */
            revision_content_sha256: string;
            /** Revision Id */
            revision_id: string;
            /**
             * Revision Record Id
             * Format: uuid
             */
            revision_record_id: string;
            /**
             * Revision Schema Version
             * @default phase4-observation-revision-v1
             * @constant
             */
            revision_schema_version: "phase4-observation-revision-v1";
            /** Revision Sequence */
            revision_sequence: number;
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** Snapshot Sha256 */
            snapshot_sha256: string;
            /** Source Record Id */
            source_record_id: string;
            /** Source Timezone */
            source_timezone: string;
            /** Unit */
            unit: string | null;
            /** Use Rights Id */
            use_rights_id: string;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
            /** Vintage Id */
            vintage_id: string;
        };
        /** OfficialDocumentEventPayload */
        OfficialDocumentEventPayload: {
            /**
             * Accepted At
             * Format: date-time
             */
            accepted_at: string;
            /** Accession Id */
            accession_id: string;
            /** Amendment Of Document Id */
            amendment_of_document_id?: string | null;
            /** Document Content Sha256 */
            document_content_sha256: string;
            document_type: components["schemas"]["OfficialDocumentType"];
            event_type: components["schemas"]["OfficialEventType"];
            /** Official Document Id */
            official_document_id: string;
            /** Official Event Id */
            official_event_id: string;
            /**
             * Official Source Version Id
             * Format: uuid
             */
            official_source_version_id: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "official_document_event";
        };
        /**
         * OfficialDocumentType
         * @enum {string}
         */
        OfficialDocumentType: "regulatory_filing" | "issuer_release" | "earnings_transcript_metadata";
        /**
         * OfficialEventType
         * @enum {string}
         */
        OfficialEventType: "filing" | "earnings" | "corporate_event";
        /** OhlcvBarPayload */
        OhlcvBarPayload: {
            /** Adjustment As Of */
            adjustment_as_of?: string | null;
            adjustment_basis: components["schemas"]["AdjustmentBasis"];
            /**
             * Bar End
             * Format: date-time
             */
            bar_end: string;
            bar_interval: components["schemas"]["BarInterval"];
            /**
             * Bar Start
             * Format: date-time
             */
            bar_start: string;
            /** Close */
            close: string;
            /**
             * Corporate Action Revision Ids
             * @default []
             */
            corporate_action_revision_ids: string[];
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Open */
            open: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "ohlcv_bar";
            /** Volume */
            volume: string;
            /**
             * Volume Unit
             * @default shares
             * @constant
             */
            volume_unit: "shares";
        };
        /**
         * QualityFlag
         * @enum {string}
         */
        QualityFlag: "synthetic_fixture" | "date_only_convention_applied" | "future_availability_excluded" | "revision_replayed_as_of" | "near_duplicate_retained";
        /** QuotedClaim */
        QuotedClaim: {
            /** Claim Id */
            claim_id: string;
            /** Exact Text */
            exact_text: string;
            /** Kind */
            kind: string;
            span: components["schemas"]["SourceSpan"];
        };
        /** RawObservation */
        RawObservation: {
            /** Adapter Id */
            adapter_id: string;
            /** Adapter Version */
            adapter_version: string;
            availability_convention: components["schemas"]["AvailabilityConvention"];
            availability_precision: components["schemas"]["AvailabilityPrecision"];
            /** Availability Source Date */
            availability_source_date?: string | null;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Calendar Id */
            calendar_id: string | null;
            /** Currency */
            currency: string | null;
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Schema Id */
            dataset_schema_id: string;
            /** Dataset Schema Version */
            dataset_schema_version: string;
            /** Entitlement Id */
            entitlement_id: string;
            /**
             * Envelope Schema Version
             * @default phase4-raw-observation-v1
             * @constant
             */
            envelope_schema_version: "phase4-raw-observation-v1";
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * Field Missingness
             * @default []
             */
            field_missingness: components["schemas"]["FieldMissingness"][];
            /** Instrument Id */
            instrument_id: string | null;
            /** Listing Id */
            listing_id: string | null;
            /** Logical Record Id */
            logical_record_id: string;
            /** Logical Record Key Sha256 */
            logical_record_key_sha256: string;
            /** Product Id */
            product_id: string;
            /** Provider Id */
            provider_id: string;
            /**
             * Quality Flags
             * @default []
             */
            quality_flags: components["schemas"]["QualityFlag"][];
            /** Raw Content Type */
            raw_content_type: string;
            /**
             * Raw Observation Id
             * Format: uuid
             */
            raw_observation_id: string;
            /** Raw Payload */
            raw_payload: string;
            /** Raw Payload Sha256 */
            raw_payload_sha256: string;
            /** Retrieved At */
            retrieved_at: string | null;
            /** Revision Id */
            revision_id: string;
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** Snapshot Sha256 */
            snapshot_sha256: string;
            /** Source Record Id */
            source_record_id: string;
            /** Source Timezone */
            source_timezone: string;
            /** Unit */
            unit: string | null;
            /** Use Rights Id */
            use_rights_id: string;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
            /** Vintage Id */
            vintage_id: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            dependencies: components["schemas"]["DependencyStatus"];
            /**
             * Service
             * @default api
             * @constant
             */
            service: "api";
            /**
             * Status
             * @default ready
             * @constant
             */
            status: "ready";
        };
        /**
         * RequiredData
         * @enum {string}
         */
        RequiredData: "point_in_time_universe" | "delisting_aware_returns" | "ohlcv" | "official_text" | "social_text" | "borrow_availability" | "full_depth_order_book" | "options_quotes_and_trades";
        /** RequiredDataEvidence */
        RequiredDataEvidence: {
            /** Claim Ids */
            claim_ids: string[];
            state: components["schemas"]["EvidenceState"];
            /** Values */
            values: components["schemas"]["RequiredData"][];
        };
        /** ResearchMapping */
        ResearchMapping: {
            canonical_family: components["schemas"]["CanonicalFamily"] | null;
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /** Card Sha256 */
            card_sha256: string;
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            /** Extraction Config Sha256 */
            extraction_config_sha256: string;
            /** Extraction Model Id */
            extraction_model_id?: string | null;
            /** Extraction Model Revision */
            extraction_model_revision?: string | null;
            /** Extraction Prompt Sha256 */
            extraction_prompt_sha256?: string | null;
            /** Extraction Prompt Version */
            extraction_prompt_version?: string | null;
            /** Extraction Request Fingerprint */
            extraction_request_fingerprint: string;
            /**
             * Extraction Request Id
             * Format: uuid
             */
            extraction_request_id: string;
            /** Extraction Schema Version */
            extraction_schema_version: string;
            /** Extractor Id */
            extractor_id: string;
            extractor_kind: components["schemas"]["ExtractorKind"];
            /** Extractor Version */
            extractor_version: string;
            /** Mapper Rule Set Sha256 */
            mapper_rule_set_sha256: string;
            /** Mapper Rule Set Version */
            mapper_rule_set_version: string;
            /**
             * Mapping Id
             * Format: uuid
             */
            mapping_id: string;
            /** Mapping Input Sha256 */
            mapping_input_sha256: string;
            /** Mapping Version */
            mapping_version: number;
            /** Matched Rule Ids */
            matched_rule_ids: components["schemas"]["MappingRuleId"][];
            /**
             * Official Corroboration Source Version Ids
             * @default []
             */
            official_corroboration_source_version_ids: string[];
            /** Rationale Template Version */
            rationale_template_version: string;
            /** Reason Codes */
            reason_codes: components["schemas"]["MappingReasonCode"][];
            /** Source Content Sha256 */
            source_content_sha256: string;
            /** Source Evidence */
            source_evidence: components["schemas"]["MappingEvidenceReference"][];
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Source Version */
            source_version: number;
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            verdict: components["schemas"]["ResearchVerdict"];
        };
        /** ResearchMemo */
        ResearchMemo: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /** Content Sha256 */
            content_sha256: string;
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            /** Markdown */
            markdown: string;
            /**
             * Memo Id
             * Format: uuid
             */
            memo_id: string;
            /**
             * Template Version
             * @default phase2-memo-v1
             * @constant
             */
            template_version: "phase2-memo-v1";
        };
        /**
         * ResearchVerdict
         * @enum {string}
         */
        ResearchVerdict: "BUILD_RESEARCH" | "DEFER" | "DEFER_READ_ONLY" | "REJECT_PLATFORM" | "NON_TESTABLE";
        /**
         * RiskAssumption
         * @enum {string}
         */
        RiskAssumption: "liquidity" | "low_latency" | "borrow_available" | "official_corroboration" | "volatility_stability";
        /** RiskAssumptionsEvidence */
        RiskAssumptionsEvidence: {
            /** Claim Ids */
            claim_ids: string[];
            state: components["schemas"]["EvidenceState"];
            /** Values */
            values: components["schemas"]["RiskAssumption"][];
        };
        /** SchemaBinding */
        SchemaBinding: {
            /** Dataset Schema Id */
            dataset_schema_id: string;
            /** Dataset Schema Version */
            dataset_schema_version: string;
        };
        /**
         * SignalFamily
         * @enum {string}
         */
        SignalFamily: "cross_sectional_ranking_claim" | "trend_or_pattern_claim" | "social_or_news_claim" | "pairs_or_divergence_claim" | "order_flow_claim" | "unusual_options_claim";
        /** SignalFamilyEvidence */
        SignalFamilyEvidence: {
            /** Claim Ids */
            claim_ids: string[];
            state: components["schemas"]["EvidenceState"];
            value: components["schemas"]["SignalFamily"] | null;
        };
        /** SnapshotBuildBlockedResult */
        SnapshotBuildBlockedResult: {
            /** Quality Findings */
            quality_findings: components["schemas"]["DataQualityFindingDraft"][];
            /** Request Fingerprint Sha256 */
            request_fingerprint_sha256: string;
            /**
             * Status
             * @default blocked
             * @constant
             */
            status: "blocked";
        };
        /** SnapshotBundle */
        SnapshotBundle: {
            /** Constituents */
            constituents: components["schemas"]["SnapshotConstituent"][];
            /** Normalized Observations */
            normalized_observations: components["schemas"]["NormalizedObservation"][];
            /** Quality Findings */
            quality_findings: components["schemas"]["DataQualityFinding"][];
            /** Raw Observations */
            raw_observations: components["schemas"]["RawObservation"][];
            /** Revisions */
            revisions: components["schemas"]["ObservationRevision"][];
            snapshot: components["schemas"]["DataSnapshot"];
        };
        /** SnapshotConstituent */
        SnapshotConstituent: {
            /** Adapter Id */
            adapter_id: string;
            /** Adapter Version */
            adapter_version: string;
            availability_convention: components["schemas"]["AvailabilityConvention"];
            availability_precision: components["schemas"]["AvailabilityPrecision"];
            /** Availability Source Date */
            availability_source_date?: string | null;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Calendar Id */
            calendar_id: string | null;
            /** Currency */
            currency: string | null;
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Schema Id */
            dataset_schema_id: string;
            /** Dataset Schema Version */
            dataset_schema_version: string;
            disposition: components["schemas"]["ConstituentDisposition"];
            /** Entitlement Id */
            entitlement_id: string;
            /**
             * Envelope Schema Version
             * @default phase4-normalized-observation-v1
             * @constant
             */
            envelope_schema_version: "phase4-normalized-observation-v1";
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * Field Missingness
             * @default []
             */
            field_missingness: components["schemas"]["FieldMissingness"][];
            /** Instrument Id */
            instrument_id: string | null;
            /** Listing Id */
            listing_id: string | null;
            /** Logical Record Id */
            logical_record_id: string;
            /** Logical Record Key Sha256 */
            logical_record_key_sha256: string;
            /** Normalized Content Sha256 */
            normalized_content_sha256: string;
            /**
             * Normalized Observation Id
             * Format: uuid
             */
            normalized_observation_id: string;
            /**
             * Observation Revision Id
             * Format: uuid
             */
            observation_revision_id: string;
            /** Product Id */
            product_id: string;
            /** Provider Id */
            provider_id: string;
            /**
             * Quality Flags
             * @default []
             */
            quality_flags: components["schemas"]["QualityFlag"][];
            /**
             * Raw Observation Id
             * Format: uuid
             */
            raw_observation_id: string;
            /** Raw Payload Sha256 */
            raw_payload_sha256: string;
            record_type: components["schemas"]["DataRecordType"];
            /** Retrieved At */
            retrieved_at: string | null;
            /** Revision Id */
            revision_id: string;
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** Snapshot Sha256 */
            snapshot_sha256: string;
            /** Source Record Id */
            source_record_id: string;
            /** Source Timezone */
            source_timezone: string;
            /** Unit */
            unit: string | null;
            /** Use Rights Id */
            use_rights_id: string;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
            /** Vintage Id */
            vintage_id: string;
        };
        /** SnapshotConstituentDraft */
        SnapshotConstituentDraft: {
            /** Adapter Id */
            adapter_id: string;
            /** Adapter Version */
            adapter_version: string;
            availability_convention: components["schemas"]["AvailabilityConvention"];
            availability_precision: components["schemas"]["AvailabilityPrecision"];
            /** Availability Source Date */
            availability_source_date?: string | null;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Calendar Id */
            calendar_id: string | null;
            /** Currency */
            currency: string | null;
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Schema Id */
            dataset_schema_id: string;
            /** Dataset Schema Version */
            dataset_schema_version: string;
            disposition: components["schemas"]["ConstituentDisposition"];
            /** Entitlement Id */
            entitlement_id: string;
            /**
             * Envelope Schema Version
             * @default phase4-normalized-observation-v1
             * @constant
             */
            envelope_schema_version: "phase4-normalized-observation-v1";
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * Field Missingness
             * @default []
             */
            field_missingness: components["schemas"]["FieldMissingness"][];
            /** Instrument Id */
            instrument_id: string | null;
            /** Listing Id */
            listing_id: string | null;
            /** Logical Record Id */
            logical_record_id: string;
            /** Logical Record Key Sha256 */
            logical_record_key_sha256: string;
            /** Normalized Content Sha256 */
            normalized_content_sha256: string;
            /**
             * Normalized Observation Id
             * Format: uuid
             */
            normalized_observation_id: string;
            /**
             * Observation Revision Id
             * Format: uuid
             */
            observation_revision_id: string;
            /** Product Id */
            product_id: string;
            /** Provider Id */
            provider_id: string;
            /**
             * Quality Flags
             * @default []
             */
            quality_flags: components["schemas"]["QualityFlag"][];
            /**
             * Raw Observation Id
             * Format: uuid
             */
            raw_observation_id: string;
            /** Raw Payload Sha256 */
            raw_payload_sha256: string;
            record_type: components["schemas"]["DataRecordType"];
            /** Retrieved At */
            retrieved_at: string | null;
            /** Revision Id */
            revision_id: string;
            /** Source Record Id */
            source_record_id: string;
            /** Source Timezone */
            source_timezone: string;
            /** Unit */
            unit: string | null;
            /** Use Rights Id */
            use_rights_id: string;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
            /** Vintage Id */
            vintage_id: string;
        };
        /** SnapshotCreateRequest */
        SnapshotCreateRequest: {
            /**
             * As Of Utc
             * Format: date-time
             */
            as_of_utc: string;
            capability: components["schemas"]["DataCapability"];
            /**
             * Mapping Id
             * Format: uuid
             */
            mapping_id: string;
            /** Mock Configuration Id */
            mock_configuration_id: string;
        };
        /** SnapshotManifest */
        SnapshotManifest: {
            payload: components["schemas"]["SnapshotManifestDraft"];
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** Snapshot Sha256 */
            snapshot_sha256: string;
        };
        /** SnapshotManifestDraft */
        SnapshotManifestDraft: {
            adapter: components["schemas"]["AdapterProfile"];
            /**
             * Canonicalization Version
             * @default phase4-canonical-json-v1
             * @constant
             */
            canonicalization_version: "phase4-canonical-json-v1";
            configuration: components["schemas"]["MockConfigurationIdentity"];
            /** Constituents */
            constituents: components["schemas"]["SnapshotConstituentDraft"][];
            mapping: components["schemas"]["AuthorizedMappingIdentity"];
            /** Quality Findings */
            quality_findings: components["schemas"]["DataQualityFindingDraft"][];
            request: components["schemas"]["SnapshotRequestParameters"];
            /** Request Fingerprint Sha256 */
            request_fingerprint_sha256: string;
            /** Schema Bindings */
            schema_bindings: components["schemas"]["SchemaBinding"][];
            /**
             * Snapshot Schema Version
             * @default phase4-data-snapshot-v1
             * @constant
             */
            snapshot_schema_version: "phase4-data-snapshot-v1";
            use_rights: components["schemas"]["UseRightsIdentity"];
        };
        /**
         * SnapshotQualityStatus
         * @enum {string}
         */
        SnapshotQualityStatus: "data_quality_accepted" | "data_quality_accepted_with_warnings";
        /** SnapshotRequestError */
        SnapshotRequestError: {
            /** Detail */
            detail: string;
        };
        /** SnapshotRequestParameters */
        SnapshotRequestParameters: {
            /**
             * As Of Utc
             * Format: date-time
             */
            as_of_utc: string;
            capability: components["schemas"]["DataCapability"];
            mapping: components["schemas"]["AuthorizedMappingIdentity"];
            /** Mock Configuration Id */
            mock_configuration_id: string;
        };
        /** SnapshotValidationErrorResponse */
        SnapshotValidationErrorResponse: {
            /** Detail */
            detail: components["schemas"]["SnapshotValidationIssue"][];
        };
        /** SnapshotValidationIssue */
        SnapshotValidationIssue: {
            /** Loc */
            loc: (string | number)[];
            /** Msg */
            msg: string;
            /** Type */
            type: string;
        };
        /**
         * SourceAuthority
         * @enum {string}
         */
        SourceAuthority: "official" | "social" | "news" | "other" | "unknown";
        /** SourceCorrectionRequest */
        SourceCorrectionRequest: {
            authority_verification_method?: components["schemas"]["AuthorityVerificationMethod"] | null;
            /** Ingest Idempotency Key */
            ingest_idempotency_key?: string | null;
            /** Official Corroboration Source Version Ids */
            official_corroboration_source_version_ids?: string[];
            /** Raw Text */
            raw_text?: string;
            /** Retrieved At Utc */
            retrieved_at_utc?: string | null;
            /** @default unknown */
            source_authority: components["schemas"]["SourceAuthority"];
            source_type: components["schemas"]["SourceType"];
            /** Source Url */
            source_url?: string | null;
        };
        /** SourceCreateResponse */
        SourceCreateResponse: {
            extraction: components["schemas"]["ExtractionRequestRecord"] | null;
            source: components["schemas"]["SourceRecord"];
            source_version: components["schemas"]["SourceVersion"];
        };
        /** SourceDetailResponse */
        SourceDetailResponse: {
            source: components["schemas"]["SourceRecord"];
            /** Versions */
            versions: components["schemas"]["SourceVersion"][];
        };
        /** SourceIntakeRequest */
        SourceIntakeRequest: {
            authority_verification_method?: components["schemas"]["AuthorityVerificationMethod"] | null;
            /** Ingest Idempotency Key */
            ingest_idempotency_key?: string | null;
            /** Official Corroboration Source Version Ids */
            official_corroboration_source_version_ids?: string[];
            /** Raw Text */
            raw_text?: string;
            /** Retrieved At Utc */
            retrieved_at_utc?: string | null;
            /** @default unknown */
            source_authority: components["schemas"]["SourceAuthority"];
            source_type: components["schemas"]["SourceType"];
            /** Source Url */
            source_url?: string | null;
        };
        /** SourceRecord */
        SourceRecord: {
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
        };
        /** SourceSpan */
        SourceSpan: {
            /** End Byte */
            end_byte: number;
            /** Segment Id */
            segment_id: string;
            /** Start Byte */
            start_byte: number;
            /** Text Sha256 */
            text_sha256: string;
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "pasted_caption" | "transcript" | "manual_notes" | "screenshot_transcript" | "url_provenance" | "synthetic_fixture";
        /** SourceVersion */
        SourceVersion: {
            authority_verification_method: components["schemas"]["AuthorityVerificationMethod"] | null;
            /** Content Sha256 */
            content_sha256: string;
            content_state: components["schemas"]["ContentState"];
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            /** Official Corroboration Source Version Ids */
            official_corroboration_source_version_ids?: string[];
            /** Parent Source Version Id */
            parent_source_version_id: string | null;
            /** Raw Text */
            raw_text: string | null;
            /** Retrieved At Utc */
            retrieved_at_utc: string | null;
            source_authority: components["schemas"]["SourceAuthority"];
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            source_type: components["schemas"]["SourceType"];
            /** Source Url */
            source_url: string | null;
            /** Source Version */
            source_version: number;
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /**
             * Supplied At Utc
             * Format: date-time
             */
            supplied_at_utc: string;
        };
        /**
         * TestabilityReason
         * @enum {string}
         */
        TestabilityReason: "missing_raw_text" | "missing_action_rule" | "ambiguous_action_rule" | "missing_forecast_horizon" | "ambiguous_forecast_horizon";
        /**
         * TestabilityStatus
         * @enum {string}
         */
        TestabilityStatus: "testable" | "non_testable";
        /** TradingIdeaCard */
        TradingIdeaCard: {
            action_rule: components["schemas"]["ActionRuleEvidence"];
            /** Ambiguity Flags */
            ambiguity_flags: components["schemas"]["AmbiguityFlag"][];
            asset_class: components["schemas"]["AssetClassEvidence"];
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            contribution_status: components["schemas"]["ContributionStatus"];
            corroboration_status: components["schemas"]["CorroborationStatus"];
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            execution_style: components["schemas"]["ExecutionStyleEvidence"];
            /** Extraction Config Sha256 */
            extraction_config_sha256: string;
            /** Extraction Model Id */
            extraction_model_id: string | null;
            /** Extraction Model Revision */
            extraction_model_revision: string | null;
            /** Extraction Prompt Sha256 */
            extraction_prompt_sha256: string | null;
            /** Extraction Prompt Version */
            extraction_prompt_version: string | null;
            /**
             * Extraction Request Id
             * Format: uuid
             */
            extraction_request_id: string;
            /** Extraction Schema Version */
            extraction_schema_version: string;
            /** Extractor Id */
            extractor_id: string;
            extractor_kind: components["schemas"]["ExtractorKind"];
            /** Extractor Version */
            extractor_version: string;
            forecast_horizon: components["schemas"]["ForecastHorizonEvidence"];
            infra_risk: components["schemas"]["InfraRisk"];
            /** Official Corroboration Source Ids */
            official_corroboration_source_ids: string[];
            /** Official Corroboration Source Version Ids */
            official_corroboration_source_version_ids: string[];
            /** Paraphrased Claim */
            paraphrased_claim: string | null;
            /** Quoted Claims */
            quoted_claims: components["schemas"]["QuotedClaim"][];
            /** Raw Text */
            raw_text: string | null;
            required_data: components["schemas"]["RequiredDataEvidence"];
            /** Research Priority Score */
            research_priority_score: null;
            risk_assumptions: components["schemas"]["RiskAssumptionsEvidence"];
            signal_family: components["schemas"]["SignalFamilyEvidence"];
            source_authority: components["schemas"]["SourceAuthority"];
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Source Url */
            source_url: string | null;
            /** Source Version */
            source_version: number;
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /**
             * Synthetic Fixture
             * @default false
             */
            synthetic_fixture: boolean;
            /** Testability Reason Codes */
            testability_reason_codes: components["schemas"]["TestabilityReason"][];
            /** Testability Score */
            testability_score: number;
            /**
             * Testability Score Method
             * @default phase2-testability-v1
             * @constant
             */
            testability_score_method: "phase2-testability-v1";
            testability_status: components["schemas"]["TestabilityStatus"];
        };
        /** UniverseMembershipPayload */
        UniverseMembershipPayload: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "universe_membership";
            status: components["schemas"]["MembershipStatus"];
            /** Universe Id */
            universe_id: string;
        };
        /** UseRightsIdentity */
        UseRightsIdentity: {
            /** Derived Data Allowed */
            derived_data_allowed: boolean;
            /** Display Allowed */
            display_allowed: boolean;
            /** Entitlement Id */
            entitlement_id: string;
            /** Non Display Allowed */
            non_display_allowed: boolean;
            /** Redistribution Allowed */
            redistribution_allowed: boolean;
            scope: components["schemas"]["UseRightsScope"];
            /** Storage Allowed */
            storage_allowed: boolean;
            /** Use Rights Id */
            use_rights_id: string;
        };
        /**
         * UseRightsScope
         * @enum {string}
         */
        UseRightsScope: "internal_test_fixture_only" | "internal_research_only";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VolatilityReturnInputPayload */
        VolatilityReturnInputPayload: {
            /** Bar Observation Ids */
            bar_observation_ids: string[];
            /** Calendar Observation Ids */
            calendar_observation_ids: string[];
            /**
             * Corporate Action Observation Ids
             * @default []
             */
            corporate_action_observation_ids: string[];
            /**
             * Delisting Observation Ids
             * @default []
             */
            delisting_observation_ids: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "volatility_return_input";
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_cards_v1_cards_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradingIdeaCard"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_card_v1_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardWithMemo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_mapping_v1_cards__card_id__mappings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingWithRationale"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memo_v1_cards__card_id__memo_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchMemo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_data_snapshots_v1_data_snapshots_get: {
        parameters: {
            query?: {
                mapping_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSnapshot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_data_snapshot_v1_data_snapshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotBundle"];
                };
            };
            /** @description Request validation, mapping authorization, or mandatory data-quality failure */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotBuildBlockedResult"] | components["schemas"]["SnapshotRequestError"] | components["schemas"]["SnapshotValidationErrorResponse"];
                };
            };
            /** @description Typed, sanitized adapter/configuration unavailability */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdapterUnavailableResult"];
                };
            };
        };
    };
    get_data_snapshot_v1_data_snapshots__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_extractions_v1_extractions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionRequestRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_extraction_v1_extractions__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionRequestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mappings_v1_mappings_get: {
        parameters: {
            query?: {
                card_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingWithRationale"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mapping_v1_mappings__mapping_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mapping_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingWithRationale"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_version_v1_source_versions__source_version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceVersion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_extraction_v1_source_versions__source_version_id__extractions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionRequestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_v1_sources_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_source_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceIntakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_v1_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_source_version_v1_sources__source_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
