import type { components, paths } from "./api.generated";

type ResearchRunCreateRequest = components["schemas"]["ResearchRunCreateRequest"];
type ResearchRunArtifact = components["schemas"]["ResearchRunArtifact"];
type ResearchRunSummary = components["schemas"]["ResearchRunSummary"];
type ResearchRunBlockedResponse = components["schemas"]["ResearchRunBlockedResponse"];
type ResearchValidationErrorResponse =
  components["schemas"]["ResearchValidationErrorResponse"];
type ResearchConfigurationId = components["schemas"]["ResearchConfigurationId"];
type TextFeatureExtraction = components["schemas"]["TextFeatureExtraction"];
type StructuredTextFeatures = components["schemas"]["StructuredTextFeatures"];
type ResearchBaselineComparison =
  components["schemas"]["ResearchBaselineComparison"];

type CreateRun = paths["/v1/research-runs"]["post"];
type ListRuns = paths["/v1/research-runs"]["get"];
type GetRun = paths["/v1/research-runs/{run_id}"]["get"];

const createRequest: ResearchRunCreateRequest = {
  mapping_id: "aaaaaaaa-aaaa-5aaa-8aaa-aaaaaaaaaaaa",
  snapshot_ids: ["bbbbbbbb-bbbb-5bbb-8bbb-bbbbbbbbbbbb"],
  research_configuration_id: "phase6-c-pass-v1",
};

const clientSuppliedMetrics: ResearchRunCreateRequest = {
  ...createRequest,
  // @ts-expect-error Metrics are computed exclusively by the server-owned Phase 5 engine.
  metrics: {},
};

const clientSuppliedHash: ResearchRunCreateRequest = {
  ...createRequest,
  // @ts-expect-error Artifact hashes are derived from immutable server-resolved evidence.
  artifact_sha256: "0".repeat(64),
};

const clientSuppliedThreshold: ResearchRunCreateRequest = {
  ...createRequest,
  // @ts-expect-error Gate thresholds are frozen server policy, never client input.
  thresholds: {},
};

const clientSuppliedTimestamp: ResearchRunCreateRequest = {
  ...createRequest,
  // @ts-expect-error Phase 6 timestamps are database- or source-owned.
  created_at_utc: "2026-07-14T00:00:00Z",
};

const clientSuppliedTrialResults: ResearchRunCreateRequest = {
  ...createRequest,
  // @ts-expect-error Trial results are generated by the server-owned Phase 5 engine.
  trial_results: [],
};

const clientSuppliedVerdict: ResearchRunCreateRequest = {
  ...createRequest,
  // @ts-expect-error Promotion state is emitted only by the unchanged Phase 5 gates.
  promotion_state: "PASS_RESEARCH",
};

const clientSuppliedResearchVerdict: ResearchRunCreateRequest = {
  ...createRequest,
  // @ts-expect-error Research verdicts are resolved from immutable server evidence.
  verdict: "BUILD_RESEARCH",
};

type Expect<Value extends true> = Value;
type Equal<Left, Right> =
  (<Type>() => Type extends Left ? 1 : 2) extends
  (<Type>() => Type extends Right ? 1 : 2)
    ? true
    : false;

type CreateBody = NonNullable<CreateRun["requestBody"]>["content"]["application/json"];
type Create201 = CreateRun["responses"][201]["content"]["application/json"];
type Create422 = CreateRun["responses"][422]["content"]["application/json"];
type List200 = ListRuns["responses"][200]["content"]["application/json"];
type Get200 = GetRun["responses"][200]["content"]["application/json"];

type CreateRequestFieldsAreIdentityOnly = Expect<
  Equal<
    keyof ResearchRunCreateRequest,
    "mapping_id" | "snapshot_ids" | "research_configuration_id"
  >
>;
type CreateBodyIsIdentityOnly = Expect<Equal<CreateBody, ResearchRunCreateRequest>>;
type CreateReturnsCompleteArtifact = Expect<Equal<Create201, ResearchRunArtifact>>;
type CreateBlockedIsTyped = Expect<
  Equal<Create422, ResearchRunBlockedResponse | ResearchValidationErrorResponse>
>;
type ListReturnsSummaries = Expect<Equal<List200, ResearchRunSummary[]>>;
type GetReturnsCompleteArtifact = Expect<Equal<Get200, ResearchRunArtifact>>;

type ExactConfigurationVocabulary = Expect<
  Equal<
    ResearchConfigurationId,
    | "phase6-a-pass-v1"
    | "phase6-a-fail-cost-v1"
    | "phase6-b-pass-v1"
    | "phase6-b-fail-crash-v1"
    | "phase6-c-pass-v1"
    | "phase6-c-fail-corroboration-v1"
  >
>;

type StructuredFeatureKeys = Expect<
  Equal<
    keyof StructuredTextFeatures,
    "novelty" | "direction" | "uncertainty" | "risk_change" | "event_tags"
  >
>;
type ForbiddenExtractionKeys = Extract<
  keyof TextFeatureExtraction,
  | "label"
  | "signal"
  | "model_decision"
  | "buy_sell_call"
  | "allocation"
  | "position_size"
  | "promotion_outcome"
  | "execution_instruction"
>;
type ExtractionBoundaryHasNoDecisionFields = Expect<Equal<ForbiddenExtractionKeys, never>>;

declare const artifact: ResearchRunArtifact;
const synthetic: true = artifact.synthetic;
const noRealPerformance: true = artifact.no_real_performance_claimed;
const notPaperApproval: true = artifact.pass_research_is_not_paper_approval;
const paperApprovalAbsent: false = artifact.paper_approval_granted;
const scoreSemantics: "research_score_only" = artifact.specification.score_semantics;
const phase5GateEvidence = artifact.phase5_evaluation.gate_codes;
const completeAttemptRegistry = artifact.attempts;
const exactSourceLineage = artifact.feature_rows.flatMap((row) =>
  row.features.flatMap((feature) => feature.source_references),
);
const exactLabelLineage = artifact.feature_rows.flatMap(
  (row) => row.label_source_references,
);
const pipelineInputSha256: string = artifact.pipeline_input_sha256;
declare const baselineComparison: ResearchBaselineComparison;
const descriptiveOnlyComparisonScope:
  "descriptive_all_prepared_rows_not_used_for_selection" =
    baselineComparison.evaluation_scope;
const comparisonWasNotUsedForSelection: false =
  baselineComparison.used_for_selection;

declare const familyA: components["schemas"]["FamilyAEvidence"];
const crossSectionRanks: components["schemas"]["CrossSectionRankEvidence"][] =
  familyA.cross_section_ranks;

declare const familyB: components["schemas"]["FamilyBEvidence"];
const rawNominalBarCount: number = familyB.raw_nominal_bar_count;
const adjustedReturnObservationCount: number =
  familyB.adjusted_return_observation_count;
const lifecycleTests: components["schemas"]["LifecycleTestEvidence"][] =
  familyB.lifecycle_tests;

declare const corroboration: components["schemas"]["SocialOfficialCorroboration"];
const exactSocialSource = corroboration.social_source_reference;
const exactOfficialSource = corroboration.official_source_reference;

declare const familyC: components["schemas"]["FamilyCEvidence"];
const sourceBackedNonTextBaseline:
  components["schemas"]["LaggedOhlcvBaselineEvidence"][] =
    familyC.non_text_baseline;
const descriptiveBaselineOnly: false =
  sourceBackedNonTextBaseline[0].used_for_selection;

type NoUpdateRun = Expect<
  Equal<paths["/v1/research-runs/{run_id}"]["put"], undefined>
>;
type NoPatchRun = Expect<
  Equal<paths["/v1/research-runs/{run_id}"]["patch"], undefined>
>;
type NoDeleteRun = Expect<
  Equal<paths["/v1/research-runs/{run_id}"]["delete"], undefined>
>;
type NoCollectionUpdate = Expect<
  Equal<paths["/v1/research-runs"]["put"], undefined>
>;
type NoCollectionPatch = Expect<
  Equal<paths["/v1/research-runs"]["patch"], undefined>
>;
type NoCollectionDelete = Expect<
  Equal<paths["/v1/research-runs"]["delete"], undefined>
>;

void [
  createRequest,
  clientSuppliedMetrics,
  clientSuppliedHash,
  clientSuppliedThreshold,
  clientSuppliedTimestamp,
  clientSuppliedTrialResults,
  clientSuppliedVerdict,
  clientSuppliedResearchVerdict,
  synthetic,
  noRealPerformance,
  notPaperApproval,
  paperApprovalAbsent,
  scoreSemantics,
  phase5GateEvidence,
  completeAttemptRegistry,
  exactSourceLineage,
  exactLabelLineage,
  pipelineInputSha256,
  descriptiveOnlyComparisonScope,
  comparisonWasNotUsedForSelection,
  crossSectionRanks,
  rawNominalBarCount,
  adjustedReturnObservationCount,
  lifecycleTests,
  exactSocialSource,
  exactOfficialSource,
  sourceBackedNonTextBaseline,
  descriptiveBaselineOnly,
];

export type {
  CreateBlockedIsTyped,
  CreateBodyIsIdentityOnly,
  CreateRequestFieldsAreIdentityOnly,
  CreateReturnsCompleteArtifact,
  ExactConfigurationVocabulary,
  ExtractionBoundaryHasNoDecisionFields,
  GetReturnsCompleteArtifact,
  ListReturnsSummaries,
  NoCollectionDelete,
  NoCollectionPatch,
  NoCollectionUpdate,
  NoDeleteRun,
  NoPatchRun,
  NoUpdateRun,
  StructuredFeatureKeys,
};
